name: music_room
description: "Music, Collaboration and mobility"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.2.2
  connectivity_plus: ^6.1.4
  flutter_facebook_auth: ^7.1.2
  uuid: ^4.5.1
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  just_audio: ^0.10.3
  just_audio_background: ^0.0.1-beta.16
  cupertino_icons: ^1.0.8
  provider: ^6.0.3
  http: ^1.4.0
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  sentry_flutter: ^8.14.2
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamBold.ttf
          weight: 700
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamBook.ttf
          weight: 400
