name: music_room
description: "Music, Collaboration and mobility"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  web_socket_channel: ^3.0.3
  just_audio: ^0.10.0
  just_audio_web: ^0.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  provider: ^6.1.4
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.3.0
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  flutter_dotenv: ^5.2.1
  form_validator: ^2.1.1
  intl: ^0.20.2
  palette_generator: ^0.3.3+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamBold.ttf
          weight: 700
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamBook.ttf
          weight: 400
