name: music_room
description: "Music, Collaboration and mobility"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.7.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  connectivity_plus: ^6.1.5
  dio: ^5.9.0
  duration: ^4.0.3
  flutter_facebook_auth: ^7.1.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_dotenv: ^5.2.1
  form_validator: ^2.1.1
  geolocator: ^14.0.2
  geolocator_web: ^4.1.3
  google_sign_in: ^6.2.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  just_audio: ^0.10.4
  just_audio_web: ^0.4.12
  phone_numbers_parser: ^9.0.3
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  responsive_framework: ^1.1.1
  provider: ^6.1.4
  palette_generator: ^0.3.3+4
  shimmer: ^3.0.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.0
  url_launcher: ^6.2.4
  universal_html: ^2.2.4
  dchs_flutter_beacon: ^0.6.4
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamBold.ttf
          weight: 700
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamBook.ttf
          weight: 400
